// schemas/collections/community.js
// Derived from the write sites listed under `writers`; see schemas/README.md.
module.exports = {
  events: {
    description:
      'One ingested action-sports event (competition, premiere, jam), keyed by dedupeKey.',
    writers: ['services/events/ingest.js', 'scripts/normalizeEventDates.js'],
    jsonSchema: {
      bsonType: 'object',
      required: [
        'source',
        'sourceId',
        'sourceUrl',
        'slug',
        'title',
        'description',
        'sports',
        'startAt',
        'endAt',
        'timezone',
        'timeTba',
        'status',
        'venue',
        'participation',
        'spectating',
        'image',
        'organizer',
        'dedupeKey',
        'externalLinks',
        'researchVerifiedAt',
        'createdAt',
        'updatedAt',
        'lastSeenAt',
      ],
      properties: {
        _id: { bsonType: 'objectId' },
        source: {
          bsonType: 'string',
          enum: ['xgames', 'boardr', 'official-calendars', 'premieres'],
        },
        sourceId: { bsonType: 'string' },
        sourceUrl: { bsonType: 'string' },
        sourceRefs: {
          bsonType: 'array',
          items: {
            bsonType: 'object',
            properties: {
              sourceId: { bsonType: 'string' },
              externalId: { bsonType: 'string' },
              url: { bsonType: 'string' },
            },
          },
        },
        slug: { bsonType: 'string' },
        title: { bsonType: 'string' },
        description: { bsonType: 'string' },
        aliases: { bsonType: 'array', items: { bsonType: 'string' } },
        sports: { bsonType: 'array', items: { bsonType: 'string' } },
        disciplines: { bsonType: 'array', items: { bsonType: 'string' } },
        eventKinds: { bsonType: 'array', items: { bsonType: 'string' } },
        intents: { bsonType: 'array', items: { bsonType: 'string' } },
        level: { bsonType: 'array', items: { bsonType: 'string' } },
        startAt: { bsonType: ['date', 'string', 'null'] },
        endAt: { bsonType: ['date', 'string', 'null'] },
        timezone: { bsonType: ['string', 'null'] },
        timeTba: { bsonType: 'bool' },
        status: { bsonType: 'string', enum: ['scheduled', 'ongoing', 'completed'] },
        isOnline: { bsonType: 'bool' },
        venue: {
          bsonType: 'object',
          properties: {
            name: { bsonType: 'string' },
            address: { bsonType: 'string' },
            city: { bsonType: 'string' },
            region: { bsonType: 'string' },
            postalCode: { bsonType: 'string' },
            country: { bsonType: 'string' },
            lat: { bsonType: ['number', 'null'] },
            lng: { bsonType: ['number', 'null'] },
          },
        },
        participation: {
          bsonType: 'object',
          properties: {
            registrationStatus: {
              bsonType: 'string',
              enum: ['open', 'unknown', 'invite_only', 'federation_only'],
            },
            registrationUrl: { bsonType: 'string' },
            eligibilityText: { bsonType: 'string' },
            divisions: { bsonType: 'array', items: { bsonType: 'string' } },
            skillLevel: { bsonType: 'string' },
            registrationNotes: { bsonType: 'string' },
          },
        },
        spectating: {
          bsonType: 'object',
          properties: {
            inPerson: { bsonType: 'bool' },
            ticketUrl: { bsonType: 'string' },
            ticketStatus: { bsonType: 'string' },
            ticketPrice: { bsonType: 'string' },
            ticketNotes: { bsonType: 'string' },
            streamUrl: { bsonType: 'string' },
            streamStatus: { bsonType: 'string' },
            broadcaster: { bsonType: 'string' },
          },
        },
        schedule: {
          bsonType: 'object',
          properties: {
            timezone: { bsonType: 'string' },
            notes: { bsonType: 'string' },
            days: { bsonType: 'array', items: { bsonType: 'object' } },
          },
        },
        image: { bsonType: 'string' },
        organizer: {
          bsonType: 'object',
          properties: {
            name: { bsonType: 'string' },
            verified: { bsonType: 'bool' },
          },
        },
        series: { bsonType: 'string' },
        resultsUrl: { bsonType: 'string' },
        sourceTrust: {
          bsonType: 'string',
          enum: [
            'registration_partner',
            'governing_body',
            'community_source',
            'organizer_and_venue',
          ],
        },
        externalLinks: {
          bsonType: 'array',
          items: {
            bsonType: 'object',
            properties: {
              kind: { bsonType: 'string' },
              label: { bsonType: 'string' },
              url: { bsonType: 'string' },
            },
          },
        },
        socialLinks: {
          bsonType: 'array',
          items: {
            bsonType: 'object',
            properties: {
              platform: { bsonType: 'string' },
              label: { bsonType: 'string' },
              url: { bsonType: 'string' },
            },
          },
        },
        media: {
          bsonType: 'object',
          properties: {
            images: { bsonType: 'array', items: { bsonType: 'string' } },
            videos: { bsonType: 'array', items: { bsonType: 'object' } },
          },
        },
        uncertaintyNotes: { bsonType: 'array', items: { bsonType: 'string' } },
        freshness: {
          bsonType: 'object',
          properties: { lastVerifiedAt: { bsonType: 'date' } },
        },
        researchVerifiedAt: { bsonType: 'date' },
        dedupeKey: { bsonType: 'string' },
        createdAt: { bsonType: 'date' },
        updatedAt: { bsonType: 'date' },
        lastSeenAt: { bsonType: 'date' },
        name: { bsonType: 'string' },
        sportTypes: { bsonType: ['array', 'string'] },
        eventType: { bsonType: 'string' },
        city: { bsonType: 'string' },
        region: { bsonType: 'string' },
        country: { bsonType: 'string' },
        startDate: { bsonType: ['date', 'string'] },
        webUrl: { bsonType: 'string' },
        url: { bsonType: 'string' },
      },
    },
    notes: [
      'Only insert path is the upsert in services/events/ingest.js (filter dedupeKey, $set everything, $setOnInsert createdAt). routes/events.js only reads and creates the startAt index.',
      'Document shape comes from the four source normalizers (services/events/xgames.js, boardr.js, official.js, premieres.js) merged through services/events/researchEnrichment.js; the required list is the intersection of what all four emit plus what ingest and enrichment always add.',
      'xgames omits disciplines, eventKinds, intents, level, sourceTrust, sourceRefs, socialLinks and media; official and premieres omit isOnline, series and resultsUrl. None of those can be required.',
      'startAt/endAt: every current writer emits a Date or null (premieres allows null startAt, boardr and xgames allow null endAt). Legacy ISO strings and empty strings exist in production; routes/events.js queries endAt $in [null, ""] to cope and scripts/normalizeEventDates.js --commit coerces them. Target: date | null.',
      'status: sources write scheduled|completed; only scripts/normalizeEventDates.js writes ongoing.',
      'slug is rewritten by ingest as the source slug plus a dash and the first six hex chars of md5(dedupeKey); unique indexes on dedupeKey and slug.',
      'aliases, schedule, uncertaintyNotes, freshness and the extra venue/participation/spectating keys (address, postalCode, divisions, ticketPrice, broadcaster, ...) are only written by the per-event override block in researchEnrichment.js.',
      'legacy: read only. name, sportTypes, eventType, city, region, country, startDate, webUrl, url are read by kaori-rag/documents.js eventDocument() and by nothing else; no current writer produces them. Pre-ingest documents in that shape will fail this required list, so audit before enabling validation.',
    ],
  },

  event_saves: {
    description: 'One user bookmarking one event; unique on (userId, eventId).',
    writers: ['routes/events.js'],
    jsonSchema: {
      bsonType: 'object',
      required: ['userId', 'eventId', 'createdAt'],
      properties: {
        _id: { bsonType: 'objectId' },
        userId: { bsonType: 'string' },
        eventId: { bsonType: 'string' },
        createdAt: { bsonType: 'date' },
      },
    },
    notes: [
      'Single writer: POST /api/events/:id/save upserts with $set of all three fields, so createdAt is bumped on every re-save rather than preserved.',
      'userId is req.user.userId, the JWT payload copy of users._id, so it is always a hex string. Target: objectId once the users side is migrated together.',
      'eventId is req.params.id verbatim and is never validated against the events collection; GET /api/events/saved returns it as-is, so clients decide whether it is an _id hex string or a slug.',
    ],
  },

  shops: {
    description:
      'One skate/snow shop in the public directory, imported from JSON and upserted by slug.',
    writers: ['scripts/import-shops.js'],
    jsonSchema: {
      bsonType: 'object',
      required: [
        'name',
        'slug',
        'description',
        'sports',
        'services',
        'address',
        'faqs',
        'pressFeatures',
        'teamRiders',
        'verified',
        'featured',
        'status',
        'sourceUrl',
        'createdAt',
        'updatedAt',
      ],
      properties: {
        _id: { bsonType: 'objectId' },
        name: { bsonType: 'string' },
        slug: { bsonType: 'string' },
        description: { bsonType: 'string' },
        sports: {
          bsonType: 'array',
          items: {
            bsonType: 'string',
            enum: [
              'skateboarding',
              'snowboarding',
              'skiing',
              'surfing',
              'bmx',
              'mtb',
              'scooter',
              'rollerblading',
              'wakeboarding',
            ],
          },
        },
        services: {
          bsonType: 'array',
          items: {
            bsonType: 'string',
            enum: ['gear', 'apparel', 'repairs', 'rentals', 'lessons', 'online'],
          },
        },
        address: {
          bsonType: 'object',
          properties: {
            street: { bsonType: 'string' },
            city: { bsonType: 'string' },
            region: { bsonType: 'string' },
            postalCode: { bsonType: 'string' },
            country: { bsonType: 'string' },
            lat: { bsonType: 'number' },
            lng: { bsonType: 'number' },
            location: { bsonType: 'object' },
          },
        },
        website: { bsonType: 'string' },
        phone: { bsonType: 'string' },
        imageUrl: { bsonType: 'string' },
        imageAlt: { bsonType: 'string' },
        imageSourceUrl: { bsonType: 'string' },
        reviewSummary: {
          bsonType: 'object',
          properties: {
            source: { bsonType: 'string', enum: ['Google'] },
            rating: { bsonType: 'number' },
            reviewCount: { bsonType: 'int' },
            summary: { bsonType: 'string' },
            sourceUrl: { bsonType: 'string' },
            asOf: { bsonType: 'date' },
          },
        },
        faqs: {
          bsonType: 'array',
          items: {
            bsonType: 'object',
            properties: {
              question: { bsonType: 'string' },
              answer: { bsonType: 'string' },
            },
          },
        },
        pressFeatures: {
          bsonType: 'array',
          items: {
            bsonType: 'object',
            properties: {
              title: { bsonType: 'string' },
              publisher: { bsonType: 'string' },
              url: { bsonType: 'string' },
              publishedAt: { bsonType: 'date' },
              summary: { bsonType: 'string' },
            },
          },
        },
        teamRiders: {
          bsonType: 'array',
          items: {
            bsonType: 'object',
            properties: {
              name: { bsonType: 'string' },
              role: { bsonType: 'string' },
              profileUrl: { bsonType: 'string' },
              sourceUrl: { bsonType: 'string' },
              imageUrl: { bsonType: 'string' },
              riderSlug: { bsonType: 'string' },
            },
          },
        },
        hours: { bsonType: ['string', 'object'] },
        socialLinks: { bsonType: 'object' },
        verified: { bsonType: 'bool' },
        featured: { bsonType: 'bool' },
        status: { bsonType: 'string', enum: ['draft', 'published'] },
        sourceUrl: { bsonType: 'string' },
        createdAt: { bsonType: 'date' },
        updatedAt: { bsonType: 'date' },
      },
    },
    notes: [
      'Script-only writer: `npm run shops:import -- --file x.json --apply` bulk-upserts by slug ($set the normalized shop, $setOnInsert createdAt). routes/shops.js never writes shops.',
      'Shape is the Joi schema in services/shops/normalizeShop.js with stripUnknown, so the required list is exactly the fields Joi defaults or requires; website, phone, imageUrl, imageAlt, imageSourceUrl, reviewSummary, hours and socialLinks are optional and absent when the import file omits them.',
      'address.location is a GeoJSON Point { type: "Point", coordinates: [lng, lat] } added only when both lat and lng are numbers; it backs the 2dsphere index.',
      'reviewSummary.asOf and pressFeatures[].publishedAt are Joi.date().iso() and arrive as real Dates because normalizeShop returns the converted value.',
      'teamRiders[].riderSlug is stored only when the import file supplies it. The riderSlug the API returns is computed at read time by services/shops/riderMatcher.js and is not written back.',
      'hours is Joi.alternatives(string, object) with no inner shape, so it is typed as either.',
      'socialLinks is a Joi pattern object (platform name -> http(s) url); keys are not enumerated.',
    ],
  },

  shop_comments: {
    description: 'One comment or reply on a shop page; soft-deleted via status.',
    writers: ['routes/shops.js'],
    jsonSchema: {
      bsonType: 'object',
      required: [
        'shopId',
        'userId',
        'parentCommentId',
        'content',
        'replyCount',
        'status',
        'createdAt',
        'updatedAt',
      ],
      properties: {
        _id: { bsonType: 'objectId' },
        shopId: { bsonType: 'string' },
        userId: { bsonType: 'string' },
        parentCommentId: { bsonType: ['string', 'null'] },
        content: { bsonType: 'string' },
        replyCount: { bsonType: 'int' },
        status: { bsonType: 'string', enum: ['active', 'deleted'] },
        createdAt: { bsonType: 'date' },
        updatedAt: { bsonType: 'date' },
      },
    },
    notes: [
      'shopId is shop._id.toString() and parentCommentId is the raw request string (validated with ObjectId.isValid), so both are hex strings that must be wrapped in new ObjectId() to join; userId is the JWT string. Target: objectId for all three.',
      'replyCount is $inc +1/-1 on the parent by the create and delete routes, so it is int; it can go negative if a reply is deleted twice through a race because the delete route checks status before writing.',
      'DELETE never removes the document: it $sets status to deleted and updatedAt; readers filter status: active.',
      'The `user` object returned by the API is populated at read time from users and is not stored.',
    ],
  },

  riders: {
    description:
      'One editorial rider profile (pro/am athlete page), distinct from users with network: true.',
    writers: [
      'services/riders/editorialRiderImporter.js',
      'scripts/import-editorial-rider-batch.js',
      'scripts/backfill-rider-photos.js',
    ],
    jsonSchema: {
      bsonType: 'object',
      required: [
        'canonicalName',
        'normalizedName',
        'aliases',
        'normalizedAliases',
        'slug',
        'identityKey',
        'primarySport',
        'disciplines',
        'nationality',
        'homeRegion',
        'biography',
        'officialWebsite',
        'socialLinks',
        'sponsors',
        'teams',
        'stance',
        'ridingStyle',
        'notableResults',
        'contestHistory',
        'signatureTricks',
        'contributions',
        'videoParts',
        'activeYears',
        'heroImage',
        'profileImage',
        'couchCredits',
        'sourceEvidence',
        'profileType',
        'claimStatus',
        'reviewStatus',
        'editorial',
        'createdAt',
        'updatedAt',
      ],
      properties: {
        _id: { bsonType: 'objectId' },
        canonicalName: { bsonType: 'string' },
        normalizedName: { bsonType: 'string' },
        aliases: { bsonType: 'array', items: { bsonType: 'string' } },
        normalizedAliases: { bsonType: 'array', items: { bsonType: 'string' } },
        slug: { bsonType: 'string' },
        identityKey: { bsonType: 'string' },
        primarySport: {
          bsonType: 'string',
          enum: [
            'skateboarding',
            'bmx',
            'snowboarding',
            'skiing',
            'mtb',
            'surfing',
            'wakeboarding',
            'rollerblading',
            'scooter',
          ],
        },
        disciplines: { bsonType: 'array', items: { bsonType: 'string' } },
        nationality: { bsonType: 'string' },
        homeRegion: { bsonType: 'string' },
        biography: { bsonType: 'string' },
        officialWebsite: { bsonType: ['string', 'null'] },
        socialLinks: {
          bsonType: 'array',
          items: {
            bsonType: 'object',
            properties: {
              platform: { bsonType: 'string' },
              url: { bsonType: ['string', 'null'] },
            },
          },
        },
        sponsors: { bsonType: 'array', items: { bsonType: 'string' } },
        teams: { bsonType: 'array', items: { bsonType: 'string' } },
        stance: { bsonType: 'string' },
        ridingStyle: { bsonType: 'string' },
        notableResults: { bsonType: 'array', items: { bsonType: 'object' } },
        contestHistory: { bsonType: 'array', items: { bsonType: 'object' } },
        signatureTricks: { bsonType: 'array', items: { bsonType: 'string' } },
        contributions: { bsonType: 'array', items: { bsonType: 'string' } },
        videoParts: { bsonType: 'array', items: { bsonType: 'object' } },
        activeYears: {
          bsonType: ['object', 'null'],
          properties: {
            from: { bsonType: ['int', 'string'] },
            to: { bsonType: ['int', 'string', 'null'] },
          },
        },
        heroImage: {
          bsonType: ['object', 'null'],
          properties: {
            url: { bsonType: ['string', 'null'] },
            alt: { bsonType: 'string' },
            rightsStatus: {
              bsonType: 'string',
              enum: ['controlled', 'licensed', 'reuse_permitted'],
            },
            rightsEvidenceUrl: { bsonType: ['string', 'null'] },
            credit: { bsonType: 'string' },
          },
        },
        profileImage: {
          bsonType: ['object', 'null'],
          properties: {
            url: { bsonType: ['string', 'null'] },
            alt: { bsonType: 'string' },
            rightsStatus: {
              bsonType: 'string',
              enum: ['controlled', 'licensed', 'reuse_permitted'],
            },
            rightsEvidenceUrl: { bsonType: ['string', 'null'] },
            credit: { bsonType: 'string' },
          },
        },
        couchCredits: {
          bsonType: 'array',
          items: {
            bsonType: 'object',
            properties: {
              filmId: { bsonType: 'string' },
              creditedName: { bsonType: 'string' },
              role: { bsonType: 'string' },
              context: { bsonType: 'string' },
              evidenceUrl: { bsonType: 'string' },
              confidence: { bsonType: 'string' },
            },
          },
        },
        sourceEvidence: {
          bsonType: 'array',
          items: {
            bsonType: 'object',
            properties: {
              url: { bsonType: 'string' },
              title: { bsonType: 'string' },
              publisher: { bsonType: 'string' },
              claimTags: { bsonType: 'array', items: { bsonType: 'string' } },
              accessedAt: { bsonType: 'date' },
            },
          },
        },
        profileType: { bsonType: 'string', enum: ['member', 'editorial', 'claimed'] },
        claimStatus: { bsonType: 'string', enum: ['unclaimed', 'pending', 'claimed'] },
        accountId: { bsonType: 'objectId' },
        reviewStatus: {
          bsonType: 'string',
          enum: ['draft', 'reviewed', 'published', 'rejected'],
        },
        editorial: {
          bsonType: 'object',
          properties: {
            batchId: { bsonType: 'string' },
            createdBy: { bsonType: 'string' },
            reviewedBy: { bsonType: 'string' },
            reviewedAt: { bsonType: ['date', 'null'] },
            notes: { bsonType: 'string' },
            importedAt: { bsonType: 'date' },
          },
        },
        createdAt: { bsonType: 'date' },
        updatedAt: { bsonType: 'date' },
        name: { bsonType: 'string' },
        displayName: { bsonType: 'string' },
        bio: { bsonType: 'string' },
        sports: { bsonType: 'array' },
        hometown: { bsonType: 'string' },
        country: { bsonType: 'string' },
      },
    },
    notes: [
      'Script-only insert: `npm run riders:import` runs importEditorialRiderBatch, which insertMany()s documents built by services/riders/editorialRider.js buildEditorialRider() inside a transaction, max three per batch, staging-locked unless --production with canary evidence. No HTTP route writes riders.',
      'buildEditorialRider emits every key on every document, so the required list is long. officialWebsite, activeYears, heroImage, profileImage, socialLinks[].url, heroImage.url/rightsEvidenceUrl and editorial.reviewedAt are emitted as JS undefined when absent; db.js sets no ignoreUndefined, so the driver stores them as null, hence the null types.',
      'accountId is the one deliberately conditional key (spread only when present) because the rider_account_unique index is sparse and would collide on null. It is a real ObjectId (normalizeAccountId wraps it).',
      'scripts/backfill-rider-photos.js is the only $set writer: it fills profileImage (all five keys as strings, rightsStatus reuse_permitted) and updatedAt for editorial riders lacking profileImage.url.',
      'notableResults, contestHistory and videoParts are safeArray() pass-throughs from the batch JSON with no validation; services/riders/repScore.js reads notableResults[].placement and activeYears.from, which is why those two are the only inner keys named.',
      'couchCredits[].filmId is passed through unvalidated; routes/riders.js wraps it with new ObjectId() only when ObjectId.isValid, so it is a hex string of couch_videos._id in practice. Target: objectId.',
      'legacy: read only. name, displayName, bio, sports, hometown, country are read by kaori-rag/documents.js riderDocument() (the users-shaped rider) and by no current writer of this collection.',
    ],
  },

  blog: {
    description: 'One admin-authored blog post, addressed by a slug derived from its title.',
    writers: ['routes/blog.js'],
    jsonSchema: {
      bsonType: 'object',
      required: ['title', 'author', 'date', 'content', 'url', 'images'],
      properties: {
        _id: { bsonType: 'objectId' },
        title: { bsonType: 'string' },
        author: { bsonType: 'string' },
        date: { bsonType: ['string', 'number'] },
        content: { bsonType: 'string' },
        url: { bsonType: 'string' },
        images: { bsonType: 'array', items: { bsonType: 'string' } },
      },
    },
    notes: [
      'date is written straight from req.body: middleware/validation.js runs Joi.validate but never replaces req.body with the converted value, so Joi.date() only gates the input (ISO string or epoch number) and the raw JSON value is stored. Target: date.',
      'PATCH /update/:id has no validation at all and $sets title, author, date, content and url from the body; PATCH /:id $sets images unvalidated. Both can store whatever a client sends.',
      'url is title.toLowerCase() with whitespace replaced by dashes; there is no unique index, so two posts with the same title collide on GET /url/:url.',
      'No createdAt or updatedAt is written; `date` is the only timestamp.',
    ],
  },

  newsletter_subscribers: {
    description: 'One email signup from the marketing site, with an optional unsubscribe stamp.',
    writers: ['routes/newsletter.js'],
    jsonSchema: {
      bsonType: 'object',
      required: ['email', 'source', 'subscribedAt', 'confirmed', 'tags'],
      properties: {
        _id: { bsonType: 'objectId' },
        email: { bsonType: 'string' },
        source: { bsonType: 'string' },
        subscribedAt: { bsonType: 'date' },
        confirmed: { bsonType: 'bool' },
        tags: { bsonType: 'array', items: { bsonType: 'string' } },
        unsubscribedAt: { bsonType: 'date' },
        active: { bsonType: 'bool' },
      },
    },
    notes: [
      'email is lower-cased on write; uniqueness is an application-level findOne, there is no unique index.',
      'confirmed is always inserted false and nothing sets it true (double opt-in is a TODO in the route).',
      'active and unsubscribedAt only appear after POST /unsubscribe $sets them; subscribe never writes active: true, so absence means subscribed.',
      'tags is always the literal ["ai-tips"] today.',
    ],
  },

  analytics_events: {
    description:
      'One client analytics event envelope, idempotent on eventId; written once via $setOnInsert.',
    writers: ['routes/analytics.js'],
    jsonSchema: {
      bsonType: 'object',
      required: [
        'eventId',
        'event',
        'name',
        'schemaVersion',
        'occurredAt',
        'receivedAt',
        'timestamp',
        'anonymousId',
        'installationId',
        'sessionId',
        'userId',
        'platform',
        'appVersion',
        'buildNumber',
        'source',
        'properties',
        'url',
        'referrer',
        'userAgent',
      ],
      properties: {
        _id: { bsonType: 'objectId' },
        eventId: { bsonType: 'string' },
        event: { bsonType: 'string' },
        name: { bsonType: 'string' },
        schemaVersion: { bsonType: 'int' },
        occurredAt: { bsonType: 'date' },
        receivedAt: { bsonType: 'date' },
        timestamp: { bsonType: 'date' },
        anonymousId: { bsonType: ['string', 'null'] },
        installationId: { bsonType: ['string', 'null'] },
        sessionId: { bsonType: ['string', 'null'] },
        userId: { bsonType: ['string', 'null'] },
        platform: { bsonType: 'string', enum: ['web', 'ios', 'android'] },
        appVersion: { bsonType: ['string', 'null'] },
        buildNumber: { bsonType: ['string', 'null'] },
        source: { bsonType: 'object' },
        properties: {
          bsonType: 'object',
          properties: {
            section: { bsonType: 'string' },
            depth_percent: { bsonType: 'number' },
            cta_name: { bsonType: 'string' },
            cta_location: { bsonType: 'string' },
            store: { bsonType: 'string' },
          },
        },
        url: { bsonType: ['string', 'null'] },
        referrer: { bsonType: ['string', 'null'] },
        userAgent: { bsonType: ['string', 'null'] },
      },
    },
    notes: [
      'Envelope is built by services/analyticsContracts.js normalizeEvent(); POST /events and POST /events/batch both upsert { eventId } with $setOnInsert, so a document is never modified after first write and a replayed eventId is a no-op.',
      '_id is the default ObjectId; eventId (client UUID or crypto.randomUUID()) is the idempotency key with a unique sparse index. The sparse flag exists because pre-contract documents have no eventId, so those legacy rows will fail this required list.',
      'event/name and timestamp/occurredAt are deliberate duplicates: the dashboards query event and timestamp, the contract exposes name and occurredAt.',
      'userId is taken from the x-auth-token JWT only (client-supplied userId is discarded), so it is the users._id hex string or null. Target: objectId | null.',
      'buildNumber is safeString(String(input.buildNumber || "")), so a numeric build arrives as a string and a missing one as null.',
      'source and properties are sanitizeProperties() output: only keys matching /^[a-z][a-z0-9_]{0,63}$/i that are not sensitive, values limited to null/bool/finite number/string(<=512)/short string-or-number arrays, whole object <=16KB. The named properties keys are the ones the dashboard aggregations group on; everything else is free-form.',
    ],
  },
};
