// schemas/collections/identity.js
// Derived from the write sites listed under `writers`; see schemas/README.md.

const id = { bsonType: 'objectId' };
const str = { bsonType: 'string' };
const strOrNull = { bsonType: ['string', 'null'] };
const bool = { bsonType: 'bool' };
const date = { bsonType: 'date' };
const dateOrNull = { bsonType: ['date', 'null'] };
const strArray = { bsonType: 'array', items: str };
const PLATFORMS = ['ios', 'android', 'web'];

module.exports = {
  users: {
    description:
      'One account: password, Google or Apple sign-in, plus profile, homies, subscription and notification preferences.',
    writers: [
      'routes/users.js',
      'routes/auth.js',
      'routes/user.js',
      'routes/image.js',
      'routes/payments.js',
      'routes/notificationPreferences.js',
      'scripts/backfillNotificationPreferences.js',
      'scripts/seed-staging-riders.js',
      'hashpasswords.js',
    ],
    jsonSchema: {
      bsonType: 'object',
      required: ['name', 'email', 'network', 'createdAt'],
      properties: {
        _id: id,
        name: str,
        email: str,
        password: str,
        isGoogleSSO: bool,
        appleUserId: str,
        imageUri: strOrNull,
        sports: strArray,
        riderProfile: {
          bsonType: 'object',
          properties: {
            nickname: str,
            age: { bsonType: ['string', 'number'] },
            height: str,
            weight: str,
            nationality: str,
            riderStyle: str,
            alternateSport: str,
            motto: str,
            dreamDate: str,
            favoriteMovie: str,
            favoriteReading: str,
            favoriteMusic: str,
            favoriteCourse: str,
            sickestTrick: str,
            greatestStrength: str,
            greatestWeakness: str,
            otherHobbies: str,
            avatarType: { enum: ['icon', 'upload'] },
            avatarIcon: { bsonType: ['object', 'null'] },
          },
        },
        network: bool,
        homies: strArray,
        homieRequests: {
          bsonType: 'object',
          properties: {
            sent: strArray,
            received: { bsonType: 'array', items: { bsonType: 'object' } },
          },
        },
        resetToken: str,
        resetTokenExpiry: { bsonType: 'number' },
        subscription: {
          bsonType: 'object',
          properties: {
            stripeCustomerId: str,
            stripeSubscriptionId: str,
            status: str,
            plan: { enum: ['free', 'premium'] },
            currentPeriodEnd: date,
            lastPaymentDate: date,
            adminOverride: str,
          },
        },
        notificationPreferences: {
          bsonType: 'object',
          properties: {
            messages: { bsonType: 'object' },
            reminders: { bsonType: 'object' },
            homies: { bsonType: 'object' },
            quietHours: { bsonType: 'object' },
            osPermission: { bsonType: 'object' },
            updatedAt: date,
          },
        },
        createdAt: date,
        updatedAt: date,
        role: str,
        isBot: bool,
        bio: str,
        location: { bsonType: ['string', 'object', 'null'] },
        botCharacter: str,
        stagingFixture: bool,
      },
    },
    notes: [
      'Three insert sites. routes/users.js POST / writes name, email, password, isGoogleSSO, sports, riderProfile, network, createdAt. routes/auth.js /google-auth writes name, email, imageUri, isGoogleSSO, network, homies, homieRequests, createdAt. routes/auth.js /apple-auth writes name, email, appleUserId, network, homies, homieRequests, createdAt. Only name, email, network, createdAt appear at all three, hence required.',
      'homies, homieRequests are absent on password accounts until the first homie action; routes/users.js POST / adds homies via $addToSet right after insert in a non-fatal try block, so a failed Kaori auto-add leaves the field missing.',
      'homies[], homieRequests.sent[] and homieRequests.received[].from are 24-hex strings (req.user.userId or req.params.id), never ObjectId; routes/users.js and routes/user.js convert with new ObjectId() at read time. Target: objectId.',
      'homieRequests.received items are { from: string, sentAt: date }, pushed by routes/users.js POST /:id/homie-request; the shape is not enforced below two levels.',
      'password: absent on SSO accounts. routes/users.js POST / stores the raw body password when isGoogleSSO is true instead of hashing it; hashpasswords.js is the one-off script that bcrypt-hashed legacy plaintext rows.',
      'name: routes/auth.js /apple-auth writes req.body.fullName unvalidated (falls back to "Apple User"); the Apple SDK can send a structured object, which would land as an object here. routes/user.js PUT /:id has no Joi schema, so name, sports, riderProfile and imageUri are whatever the client sent.',
      'imageUri: null is written when Google omits picture (mongodb ^4 serializes undefined as null; db.js does not set ignoreUndefined) or when PUT /:id sends null. routes/image.js POST / sets it for the authenticated user (auth required since 2026-09-24).',
      'resetToken and resetTokenExpiry are $set by POST /forgot-password and $unset by POST /reset-password, so neither can be required. resetTokenExpiry is Date.now() + 3600000, a JS number, not a Date.',
      'subscription is only ever written by dotted $set paths in routes/payments.js, so a partial subdoc (only stripeCustomerId) is normal. status: code writes active, canceled, past_due, and passes any Stripe subscription.status through on customer.subscription.updated, so it is not enumerated. adminOverride is req.body.override unvalidated, expected free or premium, $unset when null.',
      'subscription.stripeSubscriptionId: handleCheckoutCompleted stores session.subscription, which Stripe sends as a string id unless expanded; the same handler reads session.subscription.current_period_end, so currentPeriodEnd is new Date(NaN) on that path until customer.subscription.updated repairs it.',
      'notificationPreferences: full default subdoc from services/notificationDefaults.js is $set by routes/notificationPreferences.js PATCH (when missing) and scripts/backfillNotificationPreferences.js; PATCH then writes dotted paths. messages, reminders, homies are { push, inApp, email } booleans; quietHours is { start, end, timezone } strings (HH:MM); osPermission is { ios, android, web } each granted|denied|unknown|provisional.',
      'role: legacy, read only. No writer in this repo; middleware/authAdmin.js, routes/payments.js, routes/clientSystem.js, routes/shops.js compare it to "admin". Set by hand in Atlas.',
      'isBot, bio, location, botCharacter: legacy, read only. Projected by routes/user.js, routes/dm.js, routes/botChat.js, routes/riders.js; botCharacter is set by hand per companions/README.md. Bot users (Kaori, KAORI_BOT_ID 69c15e55c7ebe2c6884f1267) are not created by code.',
      'stagingFixture: written only by scripts/seed-staging-riders.js via replaceOne into the TrickList2Staging database, never in production.',
      'FREEMIUM_MODEL_SETUP.md documents a usage subdoc; nothing reads or writes it, middleware/subscription.js computes usage on the fly.',
      'Legacy in-memory store (store/users.js, expoPushTokens stub in API_ROUTES.md) is required by routes/users.js but unused; it never touched this collection.',
    ],
  },

  pushTokens: {
    description:
      'One Expo (or future FCM/APNs/web) push token per device, keyed by token, owned by a user.',
    writers: [
      'routes/pushTokens.js',
      'services/notificationSender.js',
      'workers/receiptsPoller.js',
    ],
    jsonSchema: {
      bsonType: 'object',
      required: [
        'token',
        'userId',
        'platform',
        'transport',
        'appVersion',
        'deviceModel',
        'locale',
        'timezone',
        'lastSeenAt',
        'deadAt',
        'deadReason',
        'createdAt',
      ],
      properties: {
        _id: id,
        token: str,
        userId: id,
        platform: { enum: PLATFORMS },
        transport: { enum: ['expo', 'fcm', 'apns', 'webpush'] },
        appVersion: strOrNull,
        deviceModel: strOrNull,
        locale: strOrNull,
        timezone: strOrNull,
        endpoint: str,
        keys: {
          bsonType: 'object',
          properties: {
            p256dh: str,
            auth: str,
          },
        },
        lastSeenAt: date,
        deadAt: dateOrNull,
        deadReason: { enum: ['DeviceNotRegistered', null] },
        createdAt: date,
      },
    },
    notes: [
      'Single write site: routes/pushTokens.js POST / does findOneAndUpdate({ token }, { $set, $setOnInsert: { token, createdAt } }, { upsert: true }); every listed required field is in that $set or $setOnInsert. Each re-register resets deadAt and deadReason to null.',
      'userId is always new ObjectId(req.user.userId) here (400 on a bad id); this is the ObjectId side of the mixed-userId split, versus the JWT string stored by client_installations and client_version_history.',
      'endpoint and keys are only written for web push registrations that send them; keys is { p256dh, auth }.',
      'services/notificationSender.js persistTickets and workers/receiptsPoller.js poll $set deadAt: new Date(), deadReason: "DeviceNotRegistered" on tokens Expo rejects. Nothing else writes deadReason, hence the enum.',
      'Indexes created in services/notificationSender.js init(): unique on token, { userId, platform }, and a TTL on deadAt (expireAfterSeconds 30d), so dead tokens are deleted a month after deadAt while live rows (deadAt null) are kept.',
      'Reads filter on { userId, deadAt: null }; a token missing deadAt (none exist from this code) would be treated as dead.',
    ],
  },

  scheduledNotifications: {
    description:
      'One planned trick-list reminder push for a user at a UTC instant; the reminder worker claims and marks it.',
    writers: ['services/reminderPlanner.js', 'workers/reminderSender.js'],
    jsonSchema: {
      bsonType: 'object',
      required: [
        'userId',
        'listId',
        'category',
        'scheduledFor',
        'status',
        'idempotencyKey',
        'attemptCount',
        'lastAttemptAt',
        'createdAt',
      ],
      properties: {
        _id: id,
        userId: id,
        listId: id,
        category: { enum: ['reminder'] },
        scheduledFor: date,
        status: { enum: ['pending', 'inflight', 'sent', 'skipped', 'cancelled', 'failed'] },
        idempotencyKey: str,
        attemptCount: { bsonType: 'int' },
        lastAttemptAt: dateOrNull,
        createdAt: date,
        claimedAt: date,
        cancelledAt: date,
        cancelledReason: { enum: ['no-unfinished-tricks'] },
        sentAt: date,
        skippedReason: {
          enum: ['self-notify', 'in-app-pref-off', 'quiet-hours', 'no-tokens', 'no-expo-tokens'],
        },
        lastError: str,
      },
    },
    notes: [
      'Single insert site: services/reminderPlanner.js planNext30Days insertMany({ ordered: false }) with all nine required fields. Duplicate idempotencyKey (sha1 of userId:listId:scheduledFor ISO) is swallowed as a rapid replan.',
      'userId and listId are ObjectId at every write (toObjectId in reminderPlanner; routes/reminderCadence.js converts req.user.userId before calling). reminderCadence GET /scheduled-notifications queries with an ObjectId too.',
      'category is the singular "reminder" here; the users.notificationPreferences key and the notificationDeliveryLog category for the same push are the plural "reminders".',
      'Lifecycle writes in workers/reminderSender.js: claim is findOneAndUpdate({ _id, status: "pending" }, { $set: { status: "inflight", claimedAt }, $inc: { attemptCount: 1 } }); markStatus then $set status plus one of cancelledReason, sentAt, skippedReason, lastError, and always lastAttemptAt. reminderPlanner planNext30Days and autoPauseStaleLists $set status: "cancelled", cancelledAt on pending future rows.',
      'attemptCount starts at 0 and only ever $inc by 1, so it stays int32. A send that throws after MAX_ATTEMPTS (3) ends in "failed"; before that the row returns to "pending" with lastError set.',
      'Indexes from reminderPlanner.init(): { scheduledFor, status }, unique idempotencyKey, { userId, listId }. No TTL; sent and cancelled rows are kept for audit.',
      'The sibling reminderCadences collection (CADENCE_COLL in the same file) is not part of this group.',
    ],
  },

  notificationDeliveryLog: {
    description:
      'One Expo push ticket per token per send, later annotated with the delivery receipt.',
    writers: ['services/notificationSender.js', 'workers/receiptsPoller.js'],
    jsonSchema: {
      bsonType: 'object',
      required: [
        'ticketId',
        'status',
        'errorCode',
        'errorMessage',
        'userId',
        'category',
        'token',
        'pushTokenId',
        'createdAt',
        'receiptStatus',
      ],
      properties: {
        _id: id,
        ticketId: strOrNull,
        status: { enum: ['ok', 'error'] },
        errorCode: strOrNull,
        errorMessage: strOrNull,
        userId: { bsonType: ['objectId', 'null'] },
        category: { enum: ['messages', 'reminders', 'homies'] },
        token: strOrNull,
        pushTokenId: { bsonType: ['objectId', 'null'] },
        createdAt: date,
        receiptStatus: { enum: ['pending', 'skipped', 'ok', 'error'] },
        receiptCheckedAt: date,
        receiptError: str,
      },
    },
    notes: [
      'Single insert site: services/notificationSender.js persistTickets insertMany({ ordered: false }); all ten required fields are set on every row. ticketId, errorCode, errorMessage are null on the opposite status; receiptStatus is "pending" for ok tickets and "skipped" for error tickets.',
      'userId is toUserObjectId(userId), which returns null for an unparsable id instead of throwing, so null is a real value here even though callers pass 24-hex strings or ObjectIds.',
      'category is whatever send() was called with: routes/dm.js "messages", workers/reminderSender.js "reminders", routes/users.js "homies". The enum lists those three callers.',
      'workers/receiptsPoller.js bulk $set receiptStatus (Expo receipt status "ok" or "error"), receiptCheckedAt, and receiptError on error, matched by ticketId.',
      'Indexes from notificationSender.init(): unique sparse ticketId, { status, createdAt }, TTL on createdAt (expireAfterSeconds 30d), so every row is deleted a month after insert.',
      'The unique sparse index still indexes ticketId: null (sparse skips only absent fields), so only one status "error" row can exist at a time; later error rows fail with 11000, which persistTickets deliberately swallows. Error tickets are effectively not logged. Fix: partialFilterExpression { ticketId: { $type: "string" } }.',
    ],
  },

  client_installations: {
    description:
      'One app install (per installationId) with its last-seen version, device metadata and optional user.',
    writers: ['routes/clientSystem.js'],
    jsonSchema: {
      bsonType: 'object',
      required: [
        'installationId',
        'platform',
        'appVersion',
        'buildNumber',
        'userId',
        'lastSeenAt',
        'updatedAt',
        'firstSeenAt',
      ],
      properties: {
        _id: id,
        installationId: { bsonType: 'string', minLength: 8, maxLength: 128 },
        platform: { enum: PLATFORMS },
        appVersion: str,
        buildNumber: str,
        osVersion: strOrNull,
        deviceModel: strOrNull,
        locale: strOrNull,
        timezone: strOrNull,
        notificationsEnabled: bool,
        userId: strOrNull,
        lastSeenAt: date,
        updatedAt: date,
        firstSeenAt: date,
      },
    },
    notes: [
      'Single write site: routes/clientSystem.js POST /heartbeat updateOne({ installationId }, { $set: doc, $setOnInsert: { firstSeenAt } }, { upsert: true }). doc is the Joi-validated body (stripUnknown) plus buildNumber coerced with String(), userId, lastSeenAt, updatedAt.',
      '_id is the driver-generated ObjectId; installationId is a client-generated string with a unique secondary index, not the primary key.',
      'userId is the raw JWT string from verifyTokenWithGrace(x-auth-token) or null for anonymous heartbeats. It is never converted to ObjectId; the admin aggregate counts it with $addToSet minus [null]. This is the string side of the mixed-userId split (pushTokens and scheduledNotifications hold ObjectId).',
      'osVersion, deviceModel, locale, timezone, notificationsEnabled are optional in the Joi schema and absent when the client omits them; the string fields also allow null and "".',
      'buildNumber arrives as string or integer and is always stored as a string.',
      'Indexes from the router factory: unique installationId, { platform, lastSeenAt: -1 }. No TTL.',
    ],
  },

  client_version_history: {
    description: 'Append-only log of every app version or build change seen on an installation.',
    writers: ['routes/clientSystem.js'],
    jsonSchema: {
      bsonType: 'object',
      required: [
        'installationId',
        'userId',
        'platform',
        'appVersion',
        'buildNumber',
        'previousVersion',
        'changedAt',
      ],
      properties: {
        _id: id,
        installationId: str,
        userId: strOrNull,
        platform: { enum: PLATFORMS },
        appVersion: str,
        buildNumber: str,
        previousVersion: strOrNull,
        changedAt: date,
      },
    },
    notes: [
      'Single insert site: routes/clientSystem.js POST /heartbeat, only when the installation is new or its appVersion or buildNumber differs from the stored row. All seven fields are written every time; never updated.',
      'userId is the same JWT string (or null) as client_installations.userId. previousVersion is null on the first heartbeat.',
      'Index: { installationId, changedAt: -1 }. No TTL.',
    ],
  },

  mobile_version_policies: {
    description:
      'One immutable revision of the forced-update policy for a platform; the highest revision wins.',
    writers: ['routes/clientSystem.js'],
    jsonSchema: {
      bsonType: 'object',
      required: [
        'platform',
        'latestVersion',
        'minimumSupportedVersion',
        'title',
        'message',
        'storeUrl',
        'effectiveAt',
        'gracePeriodHours',
        'reason',
        'revision',
        'createdAt',
        'createdBy',
      ],
      properties: {
        _id: id,
        platform: { enum: PLATFORMS },
        latestVersion: { bsonType: 'string', maxLength: 32 },
        minimumSupportedVersion: { bsonType: 'string', maxLength: 32 },
        title: { bsonType: 'string', maxLength: 100 },
        message: { bsonType: 'string', maxLength: 500 },
        storeUrl: str,
        effectiveAt: date,
        gracePeriodHours: { bsonType: 'int', minimum: 0, maximum: 720 },
        reason: { bsonType: 'string', maxLength: 500 },
        revision: { bsonType: 'int' },
        createdAt: date,
        createdBy: str,
      },
    },
    notes: [
      'Single insert site: routes/clientSystem.js PUT /admin/version-policy (admin only). The Joi-validated body (stripUnknown, gracePeriodHours defaults to 24) is spread, then effectiveAt is re-wrapped as a Date and revision, createdAt, createdBy are added. Rows are never updated or deleted.',
      '_id is the driver-generated ObjectId; the logical key is (platform, revision) with a unique index { platform: 1, revision: -1 }. currentPolicy() reads findOne({ platform }, { sort: { revision: -1 } }).',
      'revision is (latest.revision || 0) + 1, computed from a read, so two concurrent PUTs for the same platform race and the loser hits the unique index.',
      'createdBy is the admin JWT userId string, not an ObjectId.',
      'When no row exists, currentPolicy() returns an in-memory fallback with revision 0 built from LATEST_<PLATFORM>_VERSION env vars; that object is never persisted.',
    ],
  },
  reminderCadences: {
    description:
      'Per (user, list) reminder cadence choice that drives scheduledNotifications planning.',
    writers: ['services/reminderPlanner.js'],
    jsonSchema: {
      bsonType: 'object',
      required: ['userId', 'listId', 'cadence', 'updatedAt', 'pausedReason', 'createdAt'],
      properties: {
        _id: { bsonType: 'objectId' },
        userId: { bsonType: 'objectId' },
        listId: { bsonType: 'objectId' },
        cadence: { enum: ['off', 'daily', '3x-week', 'weekly'] },
        pausedReason: { enum: [null, 'auto-60d'] },
        updatedAt: { bsonType: 'date' },
        createdAt: { bsonType: 'date' },
      },
    },
    notes: [
      'Single writer: setCadence upserts on (userId, listId) with both ids coerced through toObjectId, so this is the one user-keyed collection with a single id shape.',
      'pausedReason is reset to null on every setCadence and set to auto-60d by pauseStaleCadences.',
    ],
  },
};
