// schemas/collections/media.js
// Derived from the write sites listed under `writers`; see schemas/README.md.
module.exports = {
  media_library: {
    description: 'One curated film, edit or documentary in the /api/media library.',
    writers: ['routes/media.js'],
    jsonSchema: {
      bsonType: 'object',
      required: [
        'title',
        'description',
        'type',
        'sportTypes',
        'duration',
        'releaseYear',
        'bunnyVideoId',
        'hlsUrl',
        'thumbnails',
        'athletes',
        'filmmakers',
        'productionCompany',
        'location',
        'tags',
        'difficulty',
        'tmdbId',
        'imdbId',
        'collections',
        'viewCount',
        'avgRating',
        'ratingCount',
        'totalRatingSum',
        'status',
        'featured',
        'createdAt',
        'updatedAt',
      ],
      properties: {
        _id: { bsonType: 'objectId' },
        title: { bsonType: 'string' },
        description: { bsonType: 'string' },
        type: {
          bsonType: 'string',
          enum: ['film', 'documentary', 'series', 'edit', 'tutorial', 'competition'],
        },
        sportTypes: { bsonType: 'array', items: { bsonType: 'string' } },
        duration: { bsonType: ['number', 'null'] },
        releaseYear: { bsonType: ['number', 'null'] },
        bunnyVideoId: { bsonType: ['string', 'null'] },
        hlsUrl: { bsonType: ['string', 'null'] },
        thumbnails: { bsonType: 'object' },
        athletes: {
          bsonType: 'array',
          items: { bsonType: 'object', properties: { name: { bsonType: 'string' } } },
        },
        filmmakers: { bsonType: 'array' },
        productionCompany: { bsonType: ['string', 'null'] },
        location: { bsonType: ['string', 'null'] },
        tags: { bsonType: 'array', items: { bsonType: 'string' } },
        difficulty: { bsonType: ['string', 'null'] },
        tmdbId: { bsonType: ['number', 'null'] },
        imdbId: { bsonType: ['string', 'null'] },
        collections: { bsonType: 'array' },
        viewCount: { bsonType: 'number' },
        avgRating: { bsonType: 'number' },
        ratingCount: { bsonType: 'number' },
        totalRatingSum: { bsonType: 'number' },
        status: { bsonType: 'string' },
        featured: { bsonType: 'bool' },
        publishedAt: { bsonType: ['date', 'string', 'null'], description: 'legacy: read only' },
        createdAt: { bsonType: 'date' },
        updatedAt: { bsonType: 'date' },
      },
    },
    notes: [
      'PUT /library/:id does `$set: { ...req.body, updatedAt }` and strips only _id, so any client field of any JSON type can land. The schema is deliberately open; the types above are the intended ones, not enforced ones. Dates sent through that spread arrive as strings, not BSON dates.',
      'POST /library validates only title and type; every other field is stored as sent with `x || null`, `x || []` or `x || {}` defaults, so null is written for every scalar the client omits.',
      'status: insert writes "draft"; every public read filters status: "published". No route flips it; the PUT spread is the only path. No enum because nothing restricts the set.',
      'type: enum mirrors CONTENT_TYPES in routes/media.js. sportTypes items are not validated on write; only query params are checked against SPORT_TYPES.',
      'viewCount, ratingCount, totalRatingSum: $inc counters. avgRating is recomputed as totalRatingSum / ratingCount after every rating.',
      'collections: initialised [] and never pushed to. Membership actually lives in media_collections.mediaIds.',
      'publishedAt: legacy, read only. Sort key in GET /library, /featured and /library/sport/:sportType; no writer sets it.',
      'athletes: only athletes.name is read (regex search). The rest of the element shape is client-defined. filmmakers element shape is unknown.',
      'GET /library?search= uses $text, which needs a text index that is not part of this schema.',
    ],
  },

  media_collections: {
    description: 'An editorial grouping of media_library ids for the /api/media library.',
    writers: ['routes/media.js'],
    jsonSchema: {
      bsonType: 'object',
      required: [
        'name',
        'description',
        'coverImage',
        'sportType',
        'mediaIds',
        'curatedBy',
        'featured',
        'createdAt',
        'updatedAt',
      ],
      properties: {
        _id: { bsonType: 'objectId' },
        name: { bsonType: 'string' },
        description: { bsonType: 'string' },
        coverImage: { bsonType: ['string', 'null'] },
        sportType: { bsonType: ['string', 'null'] },
        mediaIds: { bsonType: 'array', items: { bsonType: 'string' } },
        curatedBy: { bsonType: 'string', enum: ['editorial'] },
        featured: { bsonType: 'bool' },
        createdAt: { bsonType: 'date' },
        updatedAt: { bsonType: 'date' },
      },
    },
    notes: [
      'Single insert site (POST /collections). No update or delete route exists, so featured can only become true by a direct DB edit, and updatedAt never changes after insert.',
      'mediaIds: media_library._id values as hex strings from the client; readers wrap each in new ObjectId(), which throws on a malformed id. Target: objectId.',
      'curatedBy: the only writer hardcodes "editorial".',
      'sportType is singular here (one sport per collection); media_library uses sportTypes[].',
    ],
  },

  media_ratings: {
    description: 'One user star rating (1-5) on a media_library document.',
    writers: ['routes/media.js'],
    jsonSchema: {
      bsonType: 'object',
      required: ['mediaId', 'userId', 'rating', 'createdAt'],
      properties: {
        _id: { bsonType: 'objectId' },
        mediaId: { bsonType: 'string' },
        userId: { bsonType: 'string' },
        rating: { bsonType: 'number', minimum: 1, maximum: 5 },
        createdAt: { bsonType: 'date' },
        updatedAt: { bsonType: 'date' },
      },
    },
    notes: [
      'mediaId: media_library._id as a hex string (req.params.id). userId: req.user.userId, the JWT payload value, always a string. Target: objectId for both.',
      'rating: checked with `!rating || rating < 1 || rating > 5`, so a numeric string like "4" passes and would be stored as a string; the $inc on media_library that follows then fails and the rating row is orphaned. Non-integers such as 4.5 are accepted.',
      'One rating per (mediaId, userId) is enforced by findOne-then-insert only; there is no unique index.',
      'updatedAt appears only after a re-rate. deleteMany({ mediaId }) runs when the media document is deleted.',
    ],
  },

  couch_videos: {
    description: 'One film, edit or Drive-synced video in The Couch catalog (/api/couch).',
    writers: [
      'routes/couch.js',
      'scripts/import-couch-film-batch.js',
      'scripts/import-snowboard-film-batch.js',
    ],
    jsonSchema: {
      bsonType: 'object',
      required: [
        'title',
        'sportTypes',
        'viewCount',
        'isFeatured',
        'order',
        'createdAt',
        'updatedAt',
      ],
      properties: {
        _id: { bsonType: 'objectId' },
        slug: { bsonType: ['string', 'null'] },
        type: { bsonType: 'string' },
        title: { bsonType: 'string' },
        description: { bsonType: 'string' },
        sportTypes: { bsonType: 'array', items: { bsonType: 'string' } },
        tags: { bsonType: 'array', items: { bsonType: 'string' } },
        releaseYear: { bsonType: ['number', 'null'] },
        releaseSeason: { bsonType: 'string' },
        producedBy: { bsonType: 'string' },
        riders: { bsonType: 'array', items: { bsonType: 'string' } },
        sponsors: { bsonType: 'array' },
        directors: { bsonType: 'array' },
        locations: { bsonType: 'array' },
        duration: { bsonType: ['number', 'null'] },
        thumbnails: {
          bsonType: 'object',
          properties: {
            poster: { bsonType: 'string' },
            backdrop: { bsonType: 'string' },
          },
        },
        bunnyVideoId: { bsonType: ['string', 'null'] },
        hlsUrl: { bsonType: ['string', 'null'] },
        youtubeUrl: { bsonType: ['string', 'null'] },
        watchOptions: {
          bsonType: 'array',
          items: {
            bsonType: 'object',
            properties: { isOfficialPublisher: { bsonType: 'bool' } },
          },
        },
        sourceRecords: { bsonType: 'array', items: { bsonType: 'object' } },
        rights: {
          bsonType: 'object',
          properties: { hostingStatus: { bsonType: 'string' } },
        },
        availabilityStatus: { bsonType: 'string' },
        researchStatus: { bsonType: 'string' },
        seo: { bsonType: 'object' },
        isPublished: { bsonType: 'bool' },
        isFeatured: { bsonType: 'bool' },
        collectionId: { bsonType: ['string', 'null'] },
        order: { bsonType: 'number' },
        viewCount: { bsonType: 'number' },
        driveFileId: { bsonType: 'string' },
        driveFileName: { bsonType: 'string' },
        mimeType: { bsonType: 'string' },
        size: { bsonType: 'number' },
        driveThumbnail: { bsonType: ['string', 'null'] },
        driveViewLink: { bsonType: ['string', 'null'] },
        driveModifiedTime: { bsonType: 'string' },
        driveFolderId: { bsonType: 'string' },
        driveFolderName: { bsonType: 'string' },
        avgRating: { bsonType: ['number', 'null'], description: 'legacy: read only' },
        filmmaker: { bsonType: ['string', 'array', 'null'], description: 'legacy: read only' },
        trickIds: { bsonType: 'array', description: 'legacy: read only' },
        tricks: { bsonType: 'array', description: 'legacy: read only' },
        createdAt: { bsonType: 'date' },
        updatedAt: { bsonType: 'date' },
      },
    },
    notes: [
      'Four insert paths: routes/couch.js POST /admin/sync (Google Drive scan), routes/couch.js POST /admin/videos, and the upsert-by-slug in scripts/import-couch-film-batch.js and scripts/import-snowboard-film-batch.js. required is the intersection of what all four write; isPublished, type and description are not in it because the importers do not guarantee them.',
      'The import scripts do `$set: { ...film, updatedAt }` with the whole batch-JSON record, so any key in the batch file lands (researchStatus is one such key). They validate presence of slug, title, type, sportTypes, producedBy, sourceRecords and rights.hostingStatus, not types. A batch record carrying _id is written as-is on upsert-insert.',
      'slug: POST /admin/videos writes `slug || null` and POST /admin/sync omits it. The import scripts create a unique sparse index on slug; sparse still indexes null, so once that index exists the second admin-created video with slug null fails with E11000.',
      'collectionId: couch_collections._id as a hex string (compared against collection._id.toString()), or null. Target: objectId.',
      'videoId references from couch_comments and couch_reactions are strings and may be either the hex _id or the slug; see those collections.',
      'type: "film" by default and required by the importers; GET /films, kaori-tools.js searchFilms and the companion graph all filter type: "film". PUT /admin/videos/:id accepts any value, so no enum.',
      'rights.hostingStatus defaults to "external_only"; availabilityStatus defaults to "unknown" and import-couch-film-batch.js requires "available" for a published film. Neither value set is restricted in code.',
      'watchOptions[].isOfficialPublisher is the only element key the code reads (importer check for published films). sourceRecords, seo, directors, locations and sponsors element shapes are client- or batch-defined.',
      'Drive-sync fields (driveFileId, driveFileName, mimeType, size, driveThumbnail, driveViewLink, driveModifiedTime, driveFolderId, driveFolderName) exist only on documents created or refreshed by POST /admin/sync, which keys on driveFileId. driveModifiedTime is the Drive API RFC 3339 string, not a date. driveThumbnail and driveViewLink are null when Drive omits them because the driver serialises undefined as null.',
      'thumbnails: written wholesale from the client or batch file; poster and backdrop are the keys read (stream endpoint in routes/couch.js, kaori-tools.js).',
      'avgRating: legacy, read only. GET /videos?sort=rating sorts on it but nothing writes it here (ratings live on media_library). filmmaker: legacy, read only (kaori-rag/documents.js). trickIds and tricks: legacy, read only (scripts/audit-companion-graph.js). kaori-rag/documents.js also reads sport, sportType, category and url as generic fallbacks.',
      'viewCount is $inc-ed by GET /videos/:id on every public fetch, including slug lookups.',
      'bunnyVideoId, hlsUrl and driveFileId are stripped from GET /films responses by publicFilmProjection but are still stored and are returned by GET /videos/:id.',
      'Readers with no writes: routes/riders.js (slug, title by _id), kaori-tools.js, companion-graph/graph.js, kaori-rag/documents.js via scripts/index-kaori-rag.js, scripts/build-companion-graph.js, scripts/audit-companion-graph.js. scripts/youtube-to-bunny.js and services/bunnyStream.js never touch the database; the script prints JSON for manual entry through the admin UI.',
    ],
  },

  couch_collections: {
    description:
      'A named, ordered shelf in The Couch; videos point at it via couch_videos.collectionId.',
    writers: ['routes/couch.js'],
    jsonSchema: {
      bsonType: 'object',
      required: ['name', 'description', 'sportTypes', 'isPublished', 'order', 'createdAt'],
      properties: {
        _id: { bsonType: 'objectId' },
        name: { bsonType: 'string' },
        description: { bsonType: 'string' },
        sportTypes: { bsonType: 'array', items: { bsonType: 'string' } },
        isPublished: { bsonType: 'bool' },
        order: { bsonType: 'number' },
        createdAt: { bsonType: 'date' },
        updatedAt: { bsonType: 'date' },
      },
    },
    notes: [
      'POST /admin/collections hardcodes isPublished: true; PUT /admin/collections/:id can flip it and is the only writer of updatedAt.',
      'Membership lives on couch_videos.collectionId (this _id as a hex string), not on this document.',
      'Distinct from media_collections, which belongs to the /api/media library.',
    ],
  },

  couch_comments: {
    description: 'A user comment on a couch_videos document, soft-deleted via isDeleted.',
    writers: ['routes/couch.js'],
    jsonSchema: {
      bsonType: 'object',
      required: ['videoId', 'userId', 'content', 'parentCommentId', 'createdAt'],
      properties: {
        _id: { bsonType: 'objectId' },
        videoId: { bsonType: 'string' },
        userId: { bsonType: 'string' },
        content: { bsonType: 'string' },
        parentCommentId: { bsonType: ['string', 'null'] },
        isDeleted: { bsonType: 'bool' },
        deletedAt: { bsonType: 'date' },
        createdAt: { bsonType: 'date' },
      },
    },
    notes: [
      'videoId: req.params.id verbatim, so it is the couch_videos hex _id or its slug depending on which URL the client used; GET /videos/:id counts with $in over both forms. Target: objectId.',
      'userId: req.user.userId (string); the list endpoint $lookups users via $toObjectId. Target: objectId.',
      'parentCommentId is always written (null for top-level), but GET /videos/:id/comments selects top-level comments with parentCommentId: { $exists: false }, which no document written by this code satisfies. The listing is empty for current-code inserts.',
      'Soft delete only: DELETE sets isDeleted and deletedAt; reads filter isDeleted: { $ne: true }.',
    ],
  },

  couch_reactions: {
    description: 'One love or respect reaction by a user on a couch_videos document.',
    writers: ['routes/couch.js'],
    jsonSchema: {
      bsonType: 'object',
      required: ['videoId', 'userId', 'type', 'createdAt'],
      properties: {
        _id: { bsonType: 'objectId' },
        videoId: { bsonType: 'string' },
        userId: { bsonType: 'string' },
        type: { bsonType: 'string', enum: ['love', 'respect'] },
        createdAt: { bsonType: 'date' },
      },
    },
    notes: [
      'videoId: same hex-_id-or-slug ambiguity as couch_comments. Target: objectId.',
      'userId: req.user.userId (string). Target: objectId.',
      'One reaction per (videoId, userId, type) is enforced by findOne-then-insert only; removal is a hard deleteOne. No update path.',
    ],
  },

  couch_requests: {
    description: 'A user request for a film to be added to The Couch, triaged by admins.',
    writers: ['routes/couch.js'],
    jsonSchema: {
      bsonType: 'object',
      required: ['userId', 'title', 'description', 'link', 'status', 'createdAt'],
      properties: {
        _id: { bsonType: 'objectId' },
        userId: { bsonType: 'string' },
        title: { bsonType: 'string' },
        description: { bsonType: 'string' },
        link: { bsonType: 'string' },
        status: { bsonType: 'string', enum: ['pending', 'approved', 'rejected', 'fulfilled'] },
        createdAt: { bsonType: 'date' },
        updatedAt: { bsonType: 'date' },
      },
    },
    notes: [
      'status: "pending" on insert; PUT /admin/requests/:id restricts updates to the enum and is the only writer of updatedAt.',
      'userId: req.user.userId (string); the admin listing $lookups users via $toObjectId. Target: objectId.',
    ],
  },
};
